baseURL = 'https://braveseokyung.github.io/'
languageCode = 'en-us'
title = 'brog'
theme ='DoIt'
#site default theme ("light", "dark", "black", "auto")
defaultTheme = "light"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[params]
    [params.page]
        # whether to enable series navigation
        seriesNavigation=true

        [params.page.toc]
        # whether to enable the table of the contents
        enable = true

        # whether to keep the static table of the contents in front of the post
        keepStatic = false

        # whether to make the table of the contents in the sidebar automatically collapsed
        auto = true

        [params.page.code]
        # the maximum number of lines of displayed code by default
        maxShownLines = 15

        [params.page.math]
        enable = true
        blockLeftDelimiter = '$$'
        blockRightDelimiter = '$$'
        inlineLeftDelimiter = '$'
        inlineRightDelimiter = '$'
        copyTex = true
        mhchem = true

        [params.page.comment]
        enable = true
        # DoIt NEW | 0.2.5 Utterances comment config
        [params.page.comment.utterances]
          enable = true
          # owner/repo
          repo = "braveseokyung/blog"
          issueTerm = "pathname"
          label = "comment"
          lightTheme = "github-light"
          darkTheme = "github-dark"
      

# Options for taxonomies
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"